#
# Basic version of stack, for Github
#
version: "3.3"
services:
  sm_workflow_lims:
    build: .
    image: sm_workflow_lims
    depends_on:
      - mysql_server
    environment:
      - DBHOST=mysql_server
      - DBPORT=3306
      - RESET_DATABASE=$RESET_DATABASE
    entrypoint: "bash -c ./entrypoint.sh"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 4

  mysql_server:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    healthcheck:
      test: "/etc/init.d/mysql status"
      interval: 30s
      retries: 120
