#
# Extension of the stack for Local Dev environment running.
# Provides mounting code from the current folder path and
# connect to web and rabbitmq UI
version: "3.3"
services:
  sm_workflow_lims:
    ports:
      - "3000:3000"
    volumes:
      - ".:/code"

  mysql_server:
    volumes:
      - ./dockermysql:/var/lib/mysql
